# Generated by Django 2.1.3 on 2019-11-16 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='apellidoPersona',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='numeroFono',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='regionPersona',
        ),
    ]
